-- Initial TVA catalog. Re-runnable; existing records are preserved.
-- Legacy prices and images are retained. Stock and sizes must be confirmed by an administrator.
begin;
insert into public.categories(name,slug) values ('Indumentaria','indumentaria'),('Instruccionales','instruccionales') on conflict(slug) do nothing;
insert into public.products(name,slug,description,category_id,status) values ('Rashguard “Naughty by Nature”','rashguard-naughty-by-nature','Rashguard de edición limitada diseñada para entrenamientos de Jiu Jitsu No-Gi y Submission Grappling.',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-001','Por confirmar','Por confirmar',2400,0,false from public.products where slug='rashguard-naughty-by-nature' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/rashguard-naughty.jpeg','Rashguard “Naughty by Nature”',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='rashguard-naughty-by-nature' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/rashguard-naughty.jpeg');
insert into public.products(name,slug,description,category_id,status) values ('Rashguard ONYX','rashguard-onix','Rashguard manga larga con identidad TVA, diseñada para entrenamiento y competición.',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-002','Por confirmar','Por confirmar',2400,0,false from public.products where slug='rashguard-onix' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/rashguard-onyx.jpeg','Rashguard ONYX',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='rashguard-onix' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/rashguard-onyx.jpeg');
insert into public.products(name,slug,description,category_id,status) values ('Fightshort Protect Ya Neck','fightshort-protect-ya-neck','Fightshort de la colección Protect Ya Neck para Jiu Jitsu No-Gi, MMA y Submission Grappling.',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-003','Por confirmar','Por confirmar',1500,0,false from public.products where slug='fightshort-protect-ya-neck' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/fightshort-protect.jpeg','Fightshort Protect Ya Neck',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='fightshort-protect-ya-neck' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/fightshort-protect.jpeg');
insert into public.products(name,slug,description,category_id,status) values ('Colección Serpiente','coleccion-serpiente','Diseño inspirado en la identidad Dark Side de Team Vivas Academy.',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-004','Por confirmar','Por confirmar',1500,0,false from public.products where slug='coleccion-serpiente' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/fightshort-collection.jpg','Colección Serpiente',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='coleccion-serpiente' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/fightshort-collection.jpg');
insert into public.products(name,slug,description,category_id,status) values ('TVA 50/50','tva-50-50','Fightshort TVA desarrollado para libertad de movimiento durante el entrenamiento.',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-005','Por confirmar','Por confirmar',4000,0,false from public.products where slug='tva-50-50' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/tva_50_50.jpeg','TVA 50/50',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='tva-50-50' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/tva_50_50.jpeg');
insert into public.products(name,slug,description,category_id,status) values ('Hoodies TVA','hoodies-tva','Conjunto TVA disponible edición “False Reap Devils” (rojo) y “Shinobi Style” (negro).',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-006','Por confirmar','Por confirmar',4000,0,false from public.products where slug='hoodies-tva' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/hoodies.png','Hoodies TVA',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='hoodies-tva' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/hoodies.png');
insert into public.products(name,slug,description,category_id,status) values ('Rashguard Protect Ya Neck','rashguard-protect-ya-neck','Rashguard de la colección Protect Ya Neck para Jiu Jitsu No-Gi, MMA y Submission Grappling.',(select id from public.categories where slug='indumentaria'),'draft') on conflict(slug) do nothing;
insert into public.product_variants(product_id,sku,color,size,price_cents,stock,active) select id,'TVA-LEGACY-007','Por confirmar','Por confirmar',2200,0,false from public.products where slug='rashguard-protect-ya-neck' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/rash_wu_tang.jpg','Rashguard Protect Ya Neck',not exists(select 1 from public.product_images i where i.product_id=p.id and i.is_primary) from public.products p where slug='rashguard-protect-ya-neck' and not exists(select 1 from public.product_images i where i.product_id=p.id and i.url='/assets/rash_wu_tang.jpg');
insert into public.products(name,slug,description,kind,category_id,status) values ('Protect Ya Neck','protect-ya-neck','Sistema de grappling de Team Vivas Academy. Temario y precio por confirmar.','course',(select id from public.categories where slug='instruccionales'),'draft') on conflict(slug) do nothing;
insert into public.instructional_courses(product_id) select id from public.products where slug='protect-ya-neck' on conflict do nothing;
insert into public.product_images(product_id,url,alt,is_primary) select id,'/assets/protect-ya-neck.png','Protect Ya Neck',true from public.products p where slug='protect-ya-neck' and not exists(select 1 from public.product_images i where i.product_id=p.id);
commit;
